### ISSUE TITLE
Entries not showing

### ISSUE THREAD

**Issue by leafarenuk** [zaqk/todoist-list-widget#1]
hey, first thank you for the widget!
in my case the entries are not shown on the dashboard..
Don't we have to use "List" as data view?
If yes, there must be a "label" specified to make it work.

can you help?

**Comment by leafarenuk** [comment]
This is my solution for showing all items of Todoist:

After
`
        items.each do |st|
	        
	        # Add the following line:
             items_array.push({label: st['content']})
             
             # If you want to see the Due Date also, add the following line:
             items_array.push({label: st['content'], value: st['date_string']})
        
`

**Comment by zaqk** [comment]
Hey @leafarenuk  thanks for bringing this up.

You should be able to use the "Todoist" data-view found in `todoist-list-widget/dashboards/index.erb`. Try using this snippet in your main dashboard erb: 
```
<ul>
    <li data-row="1" data-col="1" data-sizex="2" data-sizey="2">
      <div data-id="todoist" data-view="Todoist" data-unordered="true" data-title="To Do"></div>
    </li>
</ul>
```
Let me know if this helps.

Also, I like the idea of incorporating the due date. My only concern is that formatting isn't built into the current UI. So if an item has a particularly verbose title then it could collide with the due date. Feel free to build that out and submit a pull request though.

**Comment by zaqk** [comment]
Hey @leafarenuk thanks for pointing this out.

Try using the "Todoist" data-view that was just committed in `todoist-list-widget/widgets/todoist/`. The "list" data-view was a default widget UI that somehow got added to this repo instead of the correct "Todoist" data-view. Test this out and let me know if you are still having issues.

Also, I like the idea of incorporating the due date. My only concern is that formatting isn't built into the current UI. So if an item has a particularly verbose title then the item title and the due date could collide. Feel free to build that out and submit a pull request though. I would definitely love to see that feature.
